services:
  postgres:
    image: postgres:17-alpine3.22
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - elk
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgsql-data:/var/lib/postgresql/data
  traefik:
    image: traefik:v3.4
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/certs:/certs:ro
  filebeat:
    image: elastic/filebeat:8.19.7
    container_name: filebeat
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - elk
    volumes:
      - ./filebeat/filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro
      # - ./filebeat/modules.d:/usr/share/filebeat/modules.d:ro
      - pgsql-data:/var/lib/pgsql/data/log:ro
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    networks:
      - elk
    # ports:
    # - "9092:9092"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_METRICS_PORT: 9997
      KAFKA_JMX_PORT: 9997
      KAFKA_NUM_PARTITIONS: 1
      # optional but nice to keep stable across restarts
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    volumes:
      - kafka-data:/var/lib/kafka/data
  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    networks:
      - proxy
      - elk
    # ports:
    # - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_METRICS_PORT=9997
      - KAFKA_CLUSTERS_0_KRAFT_ENABLED=true
      - SERVER_SERVLET_CONTEXT_PATH=/kafka
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
  logstash:
    image: logstash:8.19.7
    container_name: logstash
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks:
      - elk
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    # ports:
    # - "5044:5044"
  elasticsearch:
    image: elasticsearch:8.19.7
    container_name: elasticsearch
    networks:
      - elk
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.ml.enabled=false
    # ports:
    # - "9200:9200"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.19.7
    container_name: kibana
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    networks:
      - elk
      - proxy
    # ports:
    # - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpCaERuWEN3clRULXVQREs1Mzk0WV93
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/http_ca.crt
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
    volumes:
      - ./kibana/certs/http_ca.crt:/usr/share/kibana/config/certs/http_ca.crt:ro

networks:
  proxy:
    driver: bridge
    external: true
  elk:
    driver: bridge
    external: true

volumes:
  pgsql-data:
  es-data:
  kafka-data:
